CREATE TABLE TB_SEQUENCE (
NAME VARCHAR(10) COMMENT 'sequence name',
CURR_VALUE INT COMMENT 'current value',
INIT_VALUE INT COMMENT 'init value',
STEP INT COMMENT 'step',
MAX_VALUE INT COMMENT 'max value',
IND_STATUS VARCHAR(1) COMMENT 'status',
PRIMARY KEY(NAME)
)COMMENT='sequence table';